### ISSUE TITLE
Product Source doesn't display Product types list

### ISSUE THREAD

**Issue by wmdhosting** [matfish2/craft-tablecloth#2] opened 2022-03-16 14:35 UTC
![Snag_2224650](https://user-images.githubusercontent.com/76176291/158614466-da8bf9ac-4649-49f5-a891-af7035f151ba.png)

![Snag_222c488](https://user-images.githubusercontent.com/76176291/158614597-92b1f148-2644-48ce-9961-95459048bdb2.png)

**Comment by matfish2** [comment] 2022-03-16 14:51
"Not possible to change once saved" - This is by design (imagine you have defined columns already. Changing data source wouldn't make sense). See here: https://matanya.gitbook.io/craft-tablecloth/table-definition/data-source:
> Once you save the data source it cannot be altered. Create a new table if you require a different data source

"No product types listed" - I need to check. Once you select Product data source the "Section" dropdown should be replaced with "Product Type" like so:
![blogify-dev test_admin_tablecloth_tables_new (5)](https://user-images.githubusercontent.com/1510460/158618387-ca6a3896-22af-4ca6-86c5-d5944a58d7ef.png)

**Comment by matfish2** [comment] 2022-03-16 14:55
Any JavaScript errors in console?

**Comment by wmdhosting** [comment] 2022-03-16 14:58
![Snag_2377c3e](https://user-images.githubusercontent.com/76176291/158619996-9ebab207-abfd-4932-9960-0dee198d247f.png)

**Comment by matfish2** [comment] 2022-03-16 15:02
Please can you type `Tablecloth.productTypes` in the console and paste the output.
You should get an array:
![Screenshot 2022-03-16 17 05 23](https://user-images.githubusercontent.com/1510460/158621844-6e1484be-14eb-44ed-9e34-9caf9719cdc3.png)

**Comment by matfish2** [comment] 2022-03-16 15:12
I think I know the source of the issue. Can you select "Data source" Section and then section type "Default". Then replace data source to "Product". I think I need to reset the type selection when data source is changed.

**Comment by wmdhosting** [comment] 2022-03-16 15:16
OK. didnt get anythign with.. 
Tablecloth.productTypes

**Comment by matfish2** [comment] 2022-03-16 15:17
> OK. didnt get anythign with.. Tablecloth.productTypes

Can you share a screenshot? Was there no output at all?

**Comment by wmdhosting** [comment] 2022-03-16 15:22
after.. some swithing.. got it..

![Snag_24cdecb](https://user-images.githubusercontent.com/76176291/158625409-2d34934c-55ed-45e2-922d-cb51c165a895.png)

got it..

**Comment by wmdhosting** [comment] 2022-03-16 15:39
its ok now.. :)

**Comment by matfish2** [comment] 2022-03-16 15:40
Can you please try with 1.0.0-beta.12. Should be fixed. 
* Added a "select type" default option 
* Reset the type when data source select is changed.

**Comment by matfish2** [comment] 2022-03-16 15:40
> its ok now.. :)

Keep 'em coming :)

**Comment by wmdhosting** [comment] 2022-03-16 15:41
:)

**Closed as completed** 2022-03-16 15:40 UTC
Labels: bug
