### ISSUE TITLE
No fields in columns..

### ISSUE THREAD

**Issue by wmdhosting** [matfish2/craft-tablecloth#1] opened 2022-03-16 12:14 UTC
Looks nice..   . but Fields   do not show in columns..

Latest version of craft..
![2022-03-16_13-09-09](https://user-images.githubusercontent.com/76176291/158587416-51f9aa43-f067-4bf5-b66a-91f6d599061c.jpg)

**Comment by matfish2** [comment] 2022-03-16 12:21
Thank you for reporting. 
Can you please state which version it is? I assume you don't mean Craft 4 beta? 
Also can you please share the developer console output, as this seems like a JavaScript error.

**Comment by wmdhosting** [comment] 2022-03-16 12:25
Craft Pro 3.7.36
PHP version | 7.4.28 

Other tabs  collected fields..  just columns. not.. 
and geting this on resave..
![Snag_1aaa1f4](https://user-images.githubusercontent.com/76176291/158589322-9ce861d0-2dff-41ee-98ea-90dab4c98267.png)

**Comment by matfish2** [comment] 2022-03-16 12:32
Are you using any non-native field types on the "Novosti" entry type? (e.g Supertable or Neo)

**Comment by wmdhosting** [comment] 2022-03-16 12:37
![Snag_1b43f81](https://user-images.githubusercontent.com/76176291/158591074-9c8f021b-f8ec-48ce-9177-c139ffa15bb6.png)

Asset
Category
Redactor.. 
Tags
Entries..  
SEOmatic

**Comment by matfish2** [comment] 2022-03-16 12:48
Unable to reproduce. Seems like a Javascript visibility issue.
Can you please look at the Developer console and share any errors, in case you seem them?
Also can you please Inspect Element inside the empty Column box and tell me if you see any HTML under `div.fields`?

**Comment by wmdhosting** [comment] 2022-03-16 12:52
![Snag_1c41aa5](https://user-images.githubusercontent.com/76176291/158594033-386809a2-32a9-488f-b272-4a30d126251f.png)
no errors in console..

**Comment by wmdhosting** [comment] 2022-03-16 12:55
![Snag_1c675eb](https://user-images.githubusercontent.com/76176291/158594479-4711da88-5b99-420e-a71b-d01e65224692.png)

**Comment by matfish2** [comment] 2022-03-16 12:59
Thanks so much for your help in debugging. Can you please open the select field wrapper, like below? Should contain the list of fields.
![Screenshot 2022-03-16 14 58 29](https://user-images.githubusercontent.com/1510460/158595169-c7bfc198-b36b-4d87-b7d3-2867ff5a9c94.png)

**Comment by wmdhosting** [comment] 2022-03-16 13:04
![Snag_1ce8361](https://user-images.githubusercontent.com/76176291/158596042-f2fc22b3-4d70-4a13-aec4-715983083e5b.png)

i tryed with other  types.  Cat ,, User. same thing..

**Comment by matfish2** [comment] 2022-03-16 13:06
Seems like a pure CSS issue (maybe JS related).
The empty box is consistent with `visibility: hidden` on either `div.fields` or `div.flex-fields`. 
Can you please check? Try to disable some CSS rules and see if it makes the content show.

**Comment by wmdhosting** [comment] 2022-03-16 13:11
![Snag_1d58c48](https://user-images.githubusercontent.com/76176291/158597330-1e7be42e-d893-4cf3-be75-26f92b3c3413.png)

**Comment by wmdhosting** [comment] 2022-03-16 13:13
when i remove that. works ok...

**Comment by matfish2** [comment] 2022-03-16 13:15
I assume you have a plugin called MatrixMate installed? It seems to override the CSS for `.fields`. I will look into making the class unique.

**Comment by wmdhosting** [comment] 2022-03-16 13:17
yes :)

**Comment by matfish2** [comment] 2022-03-16 13:22
Fixed in 1.0.0-beta.11. Please check and lmk

**Comment by wmdhosting** [comment] 2022-03-16 13:26
thx .. all OK now :)

**Closed as completed** 2022-03-16 13:26 UTC
Labels: bug
